pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: CmdLine@2
  displayName: Accept Android SDK Licenses
  inputs:
    script: 'echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --licenses'
    
- task: Gradle@2
  displayName: Build Debug Application
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    tasks: 'assembleDebug'

- task: PublishPipelineArtifact@0
  displayName: Save APK
  inputs:
    artifactName: 'app-debug.apk'
    targetPath: 'app/build/outputs/apk/debug/app-debug.apk'
