name: $(SourceBranchName) $(Rev:r)
pr: none

jobs:
  - job: Dependencies
    pool:
      vmImage: 'macOS-10.13'
    ariables:
      - group: gradle
    steps:
      - task: Bash@3
        displayName: Accept Android SDK Licenses
        inputs:
          targetType: inline
          script: 'echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --licenses'
      - task: DownloadSecureFile@1
        displayName: Download google-service.json
        inputs:
          secureFile: google-services.json
      - task: Bash@3
        displayName: Copy google-service.json
        inputs:
          targetType: inline
          script: 'cp "$DOWNLOADSECUREFILE1_SECUREFILEPATH" ./app'
      - task: DownloadSecureFile@1
        displayName: Download gradle.properties
        inputs:
          secureFile: gradle.properties
      - task: Bash@3
        displayName: Copy gradle.properties
        inputs:
          targetType: inline
          script: 'mkdir -p ~/.gradle; cp "$DOWNLOADSECUREFILE2_SECUREFILEPATH" ~/.gradle'
  - job: Build
    dependsOn: Dependencies
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - task: Gradle@2
        displayName: Build Debug Application
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          tasks: 'assembleDebug'
  - job: Publish
    dependsOn: Build
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - task: PublishPipelineArtifact@0
        displayName: Save APK
        inputs:
          artifactName: 'app-debug.apk'
          targetPath: 'app/build/outputs/apk/debug/app-debug.apk'
  - job: Clean
    dependsOn: Build
    condition: always()
    steps:
      - task: Bash@3
        displayName: Delete gradle.properties
        inputs:
          targetType: inline
          script: 'rm -f ~/.gradle/gradle.properties'
